### ISSUE TITLE
Login page Issue

### ISSUE THREAD

**Issue by SadeghKrmi** [MA-Heshmatkhah/django-glrm#2]
Thanks my friend to release such a cool tool.

I am facing the issue, I have before set my login page as '/account/login' but it is showing 404 error, any extra setting in the setting is required?

LOGIN_URL='/accounts/login/'
LOGIN_REDIRECT_URL = '/polls'
LOGOUT_REDIRECT_URL = '/account/login'

**Comment by Heshmatkhah** [comment]
Hi,
I apologize for my delay.
Would you provide more information about your problem?

by the way, in my **settings.py** I have 

``` python 
LOGIN_REDIRECT_URL = reverse_lazy('some_app:some_view')
PUBLIC_PATHS = [
	r'^/accounts/.*',  # allow public access to authentication views 
]
```
