### ISSUE TITLE
Disable "next" parameter when redirect

### ISSUE THREAD

**Issue by supermario18b** [MA-Heshmatkhah/django-glrm#4]
Hi, is there a simple way to avoid to add the "next" parameter when redirecting to the login page? (Ex. /login/ instead of /login/?next=/).

Thank you for the Middleware.

supermario18b

**Comment by Heshmatkhah** [comment]
Hi
Thanks for posting this issue.
The `next` field is [redirect_field](https://docs.djangoproject.com/en/4.1/topics/auth/default/#django.contrib.auth.views.LoginView.redirect_field_name) which is part of django itself and I do nothing with it.
